# Generated by Django 6.1 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_failed_login_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
