# Generated by Django 6.1 on 2026-10-07 17:08

from django.db import migrations, models


# Backfills existing rows that still have a live `user` — their owner's name/type
# gets snapshotted now so a later account deletion doesn't lose it. Rows whose
# user is already null (account already deleted before this migration existed)
# can't be recovered; they keep showing "Deleted account" / "—" as before.
def backfill_owner_snapshot(apps, schema_editor):
    AuditLog = apps.get_model("accounts", "AuditLog")
    User = apps.get_model("accounts", "User")
    for log in AuditLog.objects.filter(user__isnull=False).select_related("user"):
        user = log.user
        name = f"{user.first_name} {user.last_name}".strip() or user.username
        if user.role == "admin":
            account_type = "Administrator"
        elif user.role == "citizen":
            account_type = "Barangay Citizen"
        else:
            account_type = user.position or "Barangay Staff"
        log.owner_name = name
        log.owner_type = account_type
        log.save(update_fields=["owner_name", "owner_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_edit_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='owner_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(backfill_owner_snapshot, migrations.RunPython.noop),
    ]
