# Generated by Django 6.1 on 2026-10-10 13:34

import orms_backend.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_backfill_admin_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
