# Generated by Django 6.1 on 2026-10-10 14:11

import orms_backend.encrypted_fields
import orms_backend.encrypted_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_encrypt_existing_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='owner_name',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='voterverification',
            name='voter_id_image',
            field=models.ImageField(storage=orms_backend.encrypted_storage.encrypted_storage, upload_to='verification/%Y/%m/'),
        ),
    ]
