# Generated by Django 6.1 on 2026-08-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_concernfolder_concern_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_action', 'In Action'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
    ]
