# Generated by Django 6.1 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_assigned_investigator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
