# Generated by Django 6.1 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportverificationcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
