# Generated by Django 6.1 on 2026-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_seed_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
