# Generated by Django 6.1 on 2026-10-01 17:11

from django.db import migrations, models


# Concerns/suggestions marked "Resolved" before the status was renamed.
def resolved_to_reviewed(apps, schema_editor):
    apps.get_model("reports", "Concern").objects.filter(status="resolved").update(status="reviewed")


def reviewed_to_resolved(apps, schema_editor):
    apps.get_model("reports", "Concern").objects.filter(status="reviewed").update(status="resolved")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=20),
        ),
        migrations.RunPython(resolved_to_reviewed, reviewed_to_resolved),
    ]
