# Generated by Django 6.1 on 2026-10-01 18:54

from django.db import migrations, models


# Concerns already marked Reviewed before this field existed: their last
# update is the best available estimate of when that happened.
def backfill(apps, schema_editor):
    from django.db.models import F

    Concern = apps.get_model("reports", "Concern")
    Concern.objects.filter(status="reviewed", reviewed_at__isnull=True).update(reviewed_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_concern_status_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
