# Generated by Django 6.1 on 2026-10-10 13:34

import orms_backend.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_investigator_last_viewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='description',
            field=orms_backend.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='concern',
            name='remarks',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nature_of_violation',
            field=orms_backend.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True),
        ),
    ]
