# Generated by Django 6.1 on 2026-10-10 14:11

import orms_backend.encrypted_fields
import orms_backend.encrypted_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_encrypt_existing_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='location',
            field=orms_backend.encrypted_fields.EncryptedTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concernattachment',
            name='file',
            field=models.FileField(storage=orms_backend.encrypted_storage.encrypted_storage, upload_to='concerns/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=orms_backend.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=orms_backend.encrypted_fields.EncryptedTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='file',
            field=models.FileField(storage=orms_backend.encrypted_storage.encrypted_storage, upload_to='reports/%Y/%m/'),
        ),
    ]
