# Generated by Django 6.1 on 2026-08-24 18:15

import ordinances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinance',
            name='pdf_file',
            field=models.FileField(storage=ordinances.models.pdf_storage, upload_to='ordinances/%Y/%m/'),
        ),
    ]
