# Generated by Django 6.1 on 2026-09-18 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0003_ordinance_is_archived_ordinance_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinanceDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_downloads', to=settings.AUTH_USER_MODEL)),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='ordinances.ordinance')),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'unique_together': {('ordinance', 'citizen')},
            },
        ),
    ]
