# Generated by Django 6.1 on 2026-09-22 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0004_ordinancedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinanceAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('city_vice_mayor', 'City/Municipal Vice Mayor'), ('city_councilor', 'City/Municipal Councilor'), ('abc_president', 'ABC Federation President (Ex-Officio)'), ('sk_federation_president', 'SK Federation President (Ex-Officio)'), ('barangay_captain', 'Punong Barangay (Barangay Captain)'), ('barangay_kagawad', 'Barangay Kagawad'), ('sk_chairperson', 'SK Chairperson')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Environment and Sanitation', 'Environment and Sanitation'), ('Peace and Order', 'Peace and Order'), ('Traffic and Transportation', 'Traffic and Transportation'), ('Public Safety', 'Public Safety'), ('Youth and Education', 'Youth and Education'), ('Social Welfare', 'Social Welfare'), ('Land Use and Housing', 'Land Use and Housing'), ('Finance and Taxation', 'Finance and Taxation'), ('Local Governance', 'Local Governance'), ('Other', 'Other')], max_length=100),
        ),
    ]
