# Generated by Django 6.1 on 2026-09-22 16:49

import uuid
from django.db import migrations, models

# Inlined rather than imported from ordinances.categories: a migration is a
# fixed historical record, so it shouldn't shift if that module's list
# changes later. This is only the STARTING set — the same 10 names
# extraction.py's OCR guesser keys off of, plus "Other" — an Administrator
# can add, rename, or retire categories from here on via the Ordinance Setup
# admin page.
INITIAL_CATEGORIES = [
    "Health",
    "Environment and Sanitation",
    "Peace and Order",
    "Traffic and Transportation",
    "Public Safety",
    "Youth and Education",
    "Social Welfare",
    "Land Use and Housing",
    "Finance and Taxation",
    "Local Governance",
    "Other",
]


def seed_categories(apps, schema_editor):
    OrdinanceCategory = apps.get_model("ordinances", "OrdinanceCategory")
    OrdinanceCategory.objects.bulk_create([OrdinanceCategory(name=name) for name in INITIAL_CATEGORIES])


def unseed_categories(apps, schema_editor):
    OrdinanceCategory = apps.get_model("ordinances", "OrdinanceCategory")
    OrdinanceCategory.objects.filter(name__in=INITIAL_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0005_ordinance_author_and_category_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ordinance categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
