# Generated by Django 6.1 on 2026-09-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0007_seed_barangay_platero_council'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinanceauthor',
            name='position',
            field=models.CharField(choices=[('barangay_captain', 'Punong Barangay (Barangay Captain)'), ('barangay_kagawad', 'Barangay Kagawad'), ('sk_chairperson', 'SK Chairperson')], max_length=30),
        ),
    ]
