# Generated by Django 6.1 on 2026-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0008_simplify_author_positions_to_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinance',
            name='kind',
            field=models.CharField(choices=[('ordinance', 'Ordinance'), ('resolution', 'Resolution')], db_index=True, default='ordinance', max_length=12),
        ),
    ]
