# Generated by Django 6.1 on 2026-10-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0009_ordinance_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinance',
            name='kind',
        ),
    ]
