# Generated by Django 6.1 on 2026-10-06 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0010_remove_ordinance_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinanceView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_views', to=settings.AUTH_USER_MODEL)),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ordinances.ordinance')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('ordinance', 'citizen')},
            },
        ),
    ]
