# Generated by Django 6.1 on 2026-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_seed_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='boundary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
