# Generated by Django 6.1 on 2026-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_refine_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='site_logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='site_name',
            field=models.CharField(default='SafeSpace', max_length=60),
        ),
    ]
