# Generated by Django 6.1 on 2026-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_barangayprofile_site_logo_barangayprofile_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='footer_legal_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='footer_notice',
            field=models.CharField(default='Personal data is processed under the Data Privacy Act of 2012 (Republic Act No. 10173).', max_length=255),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='footer_quick_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='footer_tagline',
            field=models.CharField(default='SafeSpace — Online Reporting and Management System', max_length=255),
        ),
    ]
