# Generated by Django 6.1 on 2026-10-06 12:05

from django.db import migrations, models


LEGAL_SEED = {
    "privacy": [
        {
            "anchor": "",
            "heading": "1. Who we are",
            "body": "Barangay Platero, City of Biñan, Laguna (\"the Barangay\", \"we\") is the personal information controller for SafeSpace, the Barangay's Online Reporting and Management System. We follow the Data Privacy Act of 2012 (Republic Act No. 10173), its Implementing Rules and Regulations, and issuances of the National Privacy Commission (NPC).\n\nData Protection Officer: [DPO name], [email address], [phone number], {{address}}."
        },
        {
            "anchor": "",
            "heading": "2. What we collect, why, and who sees it",
            "body": "| Data | When collected | Why we use it | Who can see it |\n| First and last name, email, mobile number, address (street and block/lot) | Sign-up | Create your account, confirm you live in Barangay Platero, contact you | You, Administrators; staff see your name and contact number on reports you file |\n| Password | Sign-up, password reset | Log you in | No one: stored only as a one-way hash |\n| Voter's ID photo | Account verification | Confirm you are a registered voter of Barangay Platero | Administrators who review accounts |\n| Profile picture (optional) | Profile page | Show on your account | You, Administrators |\n| Reports: street, date and time of incident, description, ordinance violated, photos and videos | Filing a report | Investigate and act on ordinance violations; show where incidents happen on staff dashboards | You, Barangay Captain, Investigators |\n| Concerns and suggestions, with any photos or videos | Submitting a concern | Review and respond to community concerns | You, Barangay Captain, Secretary |\n| Questions | Asking a question | Answer you; common questions may become public FAQs without your name | You, Barangay staff, Administrators |\n| One-time verification codes | Password reset, filing a report | Confirm it is really you | No one (sent only to your email) |\n| Login and logout times, audit log of actions, failed login attempts | Using the system | Security, preventing misuse, accountability of officials | Administrators |\n\nThe voter's ID is sensitive personal information under Section 3(l) of RA 10173 because it is issued by a government agency and is peculiar to you. We collect it only with your consent and use it only for verification.\n\nWe do not collect your precise location (GPS). We do not use tracking cookies, advertising or analytics tools."
        },
        {
            "anchor": "",
            "heading": "3. Our legal basis",
            "body": "- **Your consent** (Sections 12(a) and 13(a)), given at sign-up, including for your voter's ID.\n- **Functions of public authority** (Section 12(e)): receiving complaints and enforcing barangay ordinances.\n- **Compliance with a legal obligation** (Section 12(c)), when a law or court order requires us to keep or disclose data."
        },
        {
            "anchor": "",
            "heading": "4. How we share your data",
            "body": "We do not sell, rent or trade personal data. We share it only:\n\n- **Inside the Barangay:** with officials and staff whose role needs it, as shown in the table above.\n- **With service providers** that run the system for us, under our instructions: [hosting provider] runs the application; [database provider] stores accounts, reports, concerns and logs; Cloudinary stores uploaded photos, videos, voter's IDs and profile pictures; and Brevo sends system emails such as verification codes and status updates.\n- **With authorities** when required by law, a subpoena or a court order, or to protect someone's life or safety.\n\nSome of these providers store data outside the Philippines. Under Section 21 of RA 10173, the Barangay stays accountable for your data and requires these providers to protect it at a comparable level.\n\nWe do not reveal a reporter's identity to the person being reported, except when required by law or legal proceedings."
        },
        {
            "anchor": "",
            "heading": "5. How long we keep it",
            "body": "| Data | Kept for |\n| Account details | While your account is active, then [X years] after it is closed |\n| Voter's ID photo | Until your account is approved or rejected, then [deleted within X days / kept X years] |\n| Reports and concerns, with attachments | [X years] after they are resolved, or longer if needed for a legal case |\n| Audit logs and login records | [X years] |\n| Verification codes | Expire within minutes; deleted after use |\n\nWhen the retention period ends, we delete or anonymize the data securely."
        },
        {
            "anchor": "",
            "heading": "6. How we protect it",
            "body": "- All connections to the system are encrypted (HTTPS).\n- Passwords are stored only as one-way hashes.\n- Access is limited by role: each official sees only what their position needs.\n- Accounts lock for 30 minutes after 10 failed login attempts.\n- Filing a report or resetting a password requires a one-time code sent to your email.\n- Login sessions expire automatically, and actions by officials are recorded in an audit log.\n- Officials with access are bound by confidentiality."
        },
        {
            "anchor": "your-rights",
            "heading": "7. Your rights",
            "body": "Under Sections 16 to 18 of RA 10173, you have the right to:\n\n1. **Be informed** whether and how your personal data is being processed.\n2. **Access** your personal data and learn where it came from and who received it.\n3. **Correct** inaccurate or outdated data. You can edit most account details on your Profile page.\n4. **Object** to processing, or **withdraw your consent**. Some services, such as filing reports, cannot work without the data they need.\n5. **Erasure or blocking** of data that is inaccurate, unlawfully obtained or no longer needed.\n6. **Data portability:** receive a copy of your data in a common electronic format.\n7. **Damages** for harm caused by inaccurate or unlawfully used data.\n8. **File a complaint** with the National Privacy Commission ([privacy.gov.ph](https://privacy.gov.ph)).\n\nTo use these rights, contact the Data Protection Officer. We will reply within [15] working days. We may ask you to prove your identity first."
        },
        {
            "anchor": "",
            "heading": "8. Data breaches",
            "body": "If a breach is likely to put you at real risk of harm, we will notify the National Privacy Commission and affected users within 72 hours of learning of it, as required by NPC rules. The notice will say what happened, what data was involved, and what we are doing about it."
        },
        {
            "anchor": "",
            "heading": "9. Children",
            "body": "Accounts are for registered voters of Barangay Platero, so users must be at least 18 years old."
        },
        {
            "anchor": "",
            "heading": "10. Changes to this policy",
            "body": "We will post any changes here with a new effective date. For significant changes, we will notify you by email or when you next log in."
        }
    ],
    "terms": [
        {
            "anchor": "",
            "heading": "",
            "body": "By creating an account or using SafeSpace, the Barangay Platero Online Reporting and Management System, you agree to these Terms. If you do not agree, do not use the system. You can still report concerns in person at the Barangay Hall."
        },
        {
            "anchor": "",
            "heading": "1. Purpose of the system",
            "body": "SafeSpace lets residents of Barangay Platero report violations of barangay ordinances, submit concerns and suggestions, ask questions, and view barangay ordinances. It lets barangay officials receive, investigate and respond to these submissions.\n\n**SafeSpace is not an emergency service.** For emergencies, call 911 or the barangay's emergency hotline [number]."
        },
        {
            "anchor": "",
            "heading": "2. Who may use it",
            "body": "- **Residents:** you must be at least 18 years old and a registered voter of Barangay Platero. Your account becomes active only after an Administrator verifies your voter's ID.\n- **Barangay officials and staff:** accounts are created by an Administrator. Access is limited to the duties of your position."
        },
        {
            "anchor": "",
            "heading": "3. Your account",
            "body": "- Give true, complete and current information, and keep it up to date.\n- Keep your password private. Do not share your account or use someone else's.\n- You are responsible for everything done through your account. Tell the Barangay right away if you think someone else has used it.\n- One person may hold only one resident account."
        },
        {
            "anchor": "",
            "heading": "4. Filing reports and concerns",
            "body": "- Report only incidents you believe in good faith actually happened. Describe them truthfully and accurately.\n- Attach only photos and videos you took or have the right to share, and that relate to the incident.\n- To prevent abuse, the system limits how often you can file reports and may ask you to confirm your identity with a code sent to your email.\n- Filing a report does not guarantee a particular action or outcome. The Barangay decides how to act according to law and its ordinances.\n- Your report and its attachments may be used as evidence in barangay proceedings, including Katarungang Pambarangay mediation, and may be shared with authorities when the law requires."
        },
        {
            "anchor": "",
            "heading": "5. What you must not do",
            "body": "- File false, malicious or harassing reports. Knowingly false reports may lead to account suspension and liability under applicable laws, including laws on unjust vexation, perjury and libel.\n- Upload content that is obscene, violent, hateful or unrelated to the report, or that shows minors in a harmful way.\n- Post other people's personal information beyond what is needed to describe the incident.\n- Try to access data or features you are not authorized to use, disrupt the system, or bypass its security.\n- Use automated tools to create accounts or submit content.\n- Impersonate another person or a barangay official."
        },
        {
            "anchor": "",
            "heading": "6. Duties of barangay officials and staff",
            "body": "Officials and staff with access to SafeSpace must:\n\n- Use personal data only for their official duties, and keep it confidential even after leaving office.\n- Not download, copy or share personal data outside the system except as their duties require.\n- Act on reports fairly and without bias, and record their actions honestly.\n- Report any suspected data breach to the Data Protection Officer immediately.\n\nAll actions in the system are logged and may be reviewed."
        },
        {
            "anchor": "",
            "heading": "7. Suspension and termination",
            "body": "The Barangay may suspend, disable or delete an account that breaks these Terms, gives false information, or is inactive for a long time. You may ask the Data Protection Officer to close your account at any time. Records we must keep by law may be retained as described in the [Privacy Policy](privacy-policy.html)."
        },
        {
            "anchor": "",
            "heading": "8. Content you submit",
            "body": "You keep ownership of what you submit. You allow the Barangay to use, store and share it only as needed to handle your submission and to perform its official functions, as described in the Privacy Policy."
        },
        {
            "anchor": "",
            "heading": "9. Availability and limits of liability",
            "body": "We work to keep SafeSpace available and accurate, but it may be interrupted for maintenance or by technical problems. Ordinance texts in the system are for reference only; the official copies at the Barangay Hall prevail. To the extent allowed by law, the Barangay is not liable for losses caused by interruptions or by actions of users."
        },
        {
            "anchor": "",
            "heading": "10. Privacy",
            "body": "Our [Privacy Policy](privacy-policy.html) explains how we handle your personal data under the Data Privacy Act of 2012 (RA 10173), and forms part of these Terms."
        },
        {
            "anchor": "",
            "heading": "11. Changes to these Terms",
            "body": "We may update these Terms. We will post the new version with its effective date and ask you to accept significant changes when you next log in."
        },
        {
            "anchor": "",
            "heading": "12. Governing law and contact",
            "body": "These Terms are governed by the laws of the Republic of the Philippines. Questions about these Terms go to the Barangay Secretary at {{email}}, or visit us at {{address}}."
        }
    ]
}


def seed_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model("siteinfo", "LegalDocument")
    for key, sections in LEGAL_SEED.items():
        LegalDocument.objects.update_or_create(key=key, defaults={"sections": sections})



class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_barangayprofile_footer_legal_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms and Agreements')], max_length=20, unique=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_legal_documents, migrations.RunPython.noop),
    ]
