# Generated by Django 6.1 on 2026-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0008_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='effective_date',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
