# Generated by Django 6.1 on 2026-10-07 16:14

from django.db import migrations

RETENTION_SENTENCE = "Personal information will be retained by the system for operational and legal or audit purposes."


def add_retention_sentence(apps, schema_editor):
    LegalDocument = apps.get_model("siteinfo", "LegalDocument")
    try:
        terms = LegalDocument.objects.get(key="terms")
    except LegalDocument.DoesNotExist:
        return

    sections = terms.sections or []
    changed = False
    for section in sections:
        if section.get("heading", "").startswith("7.") and RETENTION_SENTENCE not in section.get("body", ""):
            section["body"] = f"{section['body']} {RETENTION_SENTENCE}"
            changed = True
            break

    if changed:
        terms.sections = sections
        terms.save(update_fields=["sections"])


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0009_legal_effective_date'),
    ]

    operations = [
        migrations.RunPython(add_retention_sentence, migrations.RunPython.noop),
    ]
